name: Android Build

on: pull_request

jobs:
  restore_cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{ hashFiles('**/*.gradle*')}}
          restore-keys: |
            ${{runner.os}}-gradle-

  set_up_jdk:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: ./gradlew test

  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: ./gradlew assemble


  upload_debug_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Apk
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk

  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true


