name: Android Build

on: pull_request

jobs:
  build_test_debug_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Android Github Action
        uses: Vukan-Markovic/Github-Android-Action@1.2




